import {
    LuLayoutDashboard,
    LuBookOpen,
    LuTrendingUp,
    LuSettings2,
    LuCalendarDays,
    LuWallet,
    LuGlobe,
    LuNotebook,
    LuLogOut,
    LuFileText,
    LuInfo,
} from "react-icons/lu";

export const SIDE_MENU_DATA = [
    {
        id: "01",
        key: "dashboard",
        label: "DASHBOARD",
        icon: LuLayoutDashboard,
        path: "/dashboard/home",
    },
    {
        id: "02",
        key: "fundamental",
        label: "FUNDAMENTAL",
        icon: LuBookOpen,
        path: "/dashboard/fundamental",
    },
    {
        id: "03",
        key: "technical",
        label: "TECHNICAL",
        icon: LuTrendingUp,
        path: "/dashboard/technical",
    },
    {
        id: "04",
        key: "options",
        label: "OPTIONS",
        icon: LuSettings2,
        path: "/dashboard/options",
    },
    {
        id: "05",
        key: "events",
        label: "EVENTS",
        icon: LuCalendarDays,
        path: "/dashboard/events",
    },
    {
        id: "06",
        key: "globalstructure",
        label: "GLOBAL",
        icon: LuGlobe,
        path: "/dashboard/globalstructure",
    },
    {
        id: "07",
        key: "wallet",
        label: "WALLET",
        icon: LuWallet,
        path: "/dashboard/wallet",
    },
    {
        id: "08",
        key: "journal",
        label: "JOURNAL",
        icon: LuNotebook,
        path: "/dashboard/journal",
    },
    {
        id: "09",
        key: "manual",
        label: "MANUAL",
        icon: LuFileText,
        path: "/dashboard/manual",
    },
    {
        id: "10",
        key: "about",
        label: "ABOUT",
        icon: LuInfo,
        path: "/dashboard/about",
    },
    {
        id: "11",
        key: "logout",
        label: "LOGOUT",
        icon: LuLogOut,
        path: "/logout",
    },
];
