const stockTips = [
  "Trade with the trend, not against it",
  "Higher timeframe controls lower timeframe",
  "Protect capital before chasing profits",
  "Risk management is the real edge",
  "Cut losses quickly, let winners run",
  "Price action beats indicators",
  "Volume confirms the move",
  "Never trade without a plan",
  "Consistency beats big wins",
  "Avoid overtrading — patience pays",
  "Markets reward discipline, not emotion",
  "Trade setups, not opinions",
  "Capital preservation comes first",
  "Risk only what you can afford to lose",
  "Strong trends ignore overbought signals",
  "Sideways markets punish impatience",
  "Wait for confirmation, not hope",
  "News creates volatility, not direction",
  "Support and resistance guide entries",
  "Liquidity runs before reversals",
  "Breakouts need volume to sustain",
  "No setup is also a setup",
  "Focus on probability, not prediction",
  "One good trade beats ten random ones",
  "Trend ends when structure breaks",
  "Markets move in cycles, learn them",
  "Emotionless trading is profitable trading",
  "The best trades feel boring",
  "Stop losses define professionals",
  "Trade less, think more",
  "Don’t marry a position",
  "Losses are tuition, learn from them",
  "Smart money leaves clues",
  "Chasing price kills accounts",
  "Big moves start quietly",
  "Wait for your level",
  "Discipline builds confidence",
  "Charts reflect human psychology",
  "Trade the market you see",
  "Avoid revenge trading",
  "Risk reward matters more than win rate",
  "Markets punish ego",
  "Trade quality over quantity",
  "Momentum fades before reversal",
  "Protect profits aggressively",
  "Volatility is opportunity with risk",
  "Plan the trade, trade the plan",
  "No emotions, only execution",
  "Your edge is patience"
];


export default stockTips;
