import db, { initLocalDb } from './backend/config/localDb.js';

initLocalDb();

try {
    db.prepare("INSERT INTO market_broadcast_cache (cache_key, payload_json, fetched_at) VALUES ('breadth', ?, CURRENT_TIMESTAMP) ON CONFLICT(cache_key) DO UPDATE SET payload_json = excluded.payload_json, fetched_at = CURRENT_TIMESTAMP");
    console.log('1. breadth OK');
    db.prepare("INSERT INTO global_cache (symbol_id, value, hi_52, lo_52, pct_change, source, fetched_at) VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(symbol_id) DO UPDATE SET value = excluded.value, hi_52 = excluded.hi_52, lo_52 = excluded.lo_52, pct_change = excluded.pct_change, source = excluded.source, fetched_at = CURRENT_TIMESTAMP");
    console.log('2. global OK');
    db.prepare("INSERT INTO fii_dii_history (date, fii_json, dii_json, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(date) DO UPDATE SET fii_json = excluded.fii_json, dii_json = excluded.dii_json, updated_at = CURRENT_TIMESTAMP");
    console.log('3. fii_dii OK');
    db.prepare("INSERT INTO chart_drawings (instrument_key, timeframe, drawings_json, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(instrument_key, timeframe) DO UPDATE SET drawings_json = excluded.drawings_json, updated_at = CURRENT_TIMESTAMP");
    console.log('4. drawings OK');
    db.prepare("INSERT INTO technicals_cache (instrument_key, timeframe, candles_count, ema_20, ema_50, ema_200, sma_50, sma_200, adx, adx_plus_di, adx_minus_di, supertrend, supertrend_direction, beta_correlation, rsi, macd_line, macd_signal, macd_histogram, stoch_rsi, stoch_k, stoch_d, williams_r, bb_upper, bb_middle, bb_lower, bb_pb, atr, kc_upper, kc_middle, kc_lower, volume_sma, obv, cmf, vwap, support, resistance, pivot_p, pivot_r1, pivot_s1, pivot_r2, pivot_s2, fib_0, fib_236, fib_382, fib_500, fib_618, fib_100, trendline_slope, trendline_r2, trendline_std_err, breadth_ratio, ad_line, mcclellan, nh_nl, trin, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(instrument_key) DO UPDATE SET timeframe=excluded.timeframe, candles_count=excluded.candles_count, ema_20=excluded.ema_20, ema_50=excluded.ema_50, ema_200=excluded.ema_200, sma_50=excluded.sma_50, sma_200=excluded.sma_200, adx=excluded.adx, adx_plus_di=excluded.adx_plus_di, adx_minus_di=excluded.adx_minus_di, supertrend=excluded.supertrend, supertrend_direction=excluded.supertrend_direction, beta_correlation=excluded.beta_correlation, rsi=excluded.rsi, macd_line=excluded.macd_line, macd_signal=excluded.macd_signal, macd_histogram=excluded.macd_histogram, stoch_rsi=excluded.stoch_rsi, stoch_k=excluded.stoch_k, stoch_d=excluded.stoch_d, williams_r=excluded.williams_r, bb_upper=excluded.bb_upper, bb_middle=excluded.bb_middle, bb_lower=excluded.bb_lower, bb_pb=excluded.bb_pb, atr=excluded.atr, kc_upper=excluded.kc_upper, kc_middle=excluded.kc_middle, kc_lower=excluded.kc_lower, volume_sma=excluded.volume_sma, obv=excluded.obv, cmf=excluded.cmf, vwap=excluded.vwap, support=excluded.support, resistance=excluded.resistance, pivot_p=excluded.pivot_p, pivot_r1=excluded.pivot_r1, pivot_s1=excluded.pivot_s1, pivot_r2=excluded.pivot_r2, pivot_s2=excluded.pivot_s2, fib_0=excluded.fib_0, fib_236=excluded.fib_236, fib_382=excluded.fib_382, fib_500=excluded.fib_500, fib_618=excluded.fib_618, fib_100=excluded.fib_100, trendline_slope=excluded.trendline_slope, trendline_r2=excluded.trendline_r2, trendline_std_err=excluded.trendline_std_err, breadth_ratio=excluded.breadth_ratio, ad_line=excluded.ad_line, mcclellan=excluded.mcclellan, nh_nl=excluded.nh_nl, trin=excluded.trin, updated_at=CURRENT_TIMESTAMP");
    console.log('5. technicals OK');
} catch(e) { console.error(e) }
