// Generated mapping of Nifty 50 symbols to Upstox Instrument Keys
export const NIFTY_50_SYMBOLS = ["RELIANCE","TCS","HDFCBANK","ICICIBANK","BHARTIARTL","SBIN","INFY","LT","ITC","BAJFINANCE","AXISBANK","KOTAKBANK","TATAMOTORS","M&M","HCLTECH","SUNPHARMA","MARUTI","TATASTEEL","ULTRACEMCO","ASIANPAINT","NTPC","TITAN","POWERGRID","BAJAJFINSV","ONGC","COALINDIA","ADANIENT","ADANIPORTS","HINDUNILVR","WIPRO","JSWSTEEL","GRASIM","HINDALCO","TECHM","NESTLEIND","CIPLA","DRREDDY","EICHERMOT","APOLLOHOSP","DIVISLAB","HEROMOTOCO","BAJAJ-AUTO","BRITANNIA","TATACONSUM","INDUSINDBK","SBILIFE","HDFCLIFE","BPCL","SHRIRAMFIN","LTIM"];

export const NIFTY_50_MAPPING = {};

export const getNifty50Keys = () => NIFTY_50_SYMBOLS.map(sym => NIFTY_50_MAPPING[sym]).filter(Boolean);
